apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-component-child-gkzf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-royw-tenant/build-suite-component-update-jtln/multi-component-child-gkzf@sha256:36f54521277ab0d760f7ccffc515812f6e1b5f7c5108383b6005cfe3752209b3
        name: container-image
        resources: {}
status: {}
