apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: multi-component-child-gkzf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: multi-component-child-gkzf
    app.kubernetes.io/part-of: build-suite-component-update-jtln
  name: multi-component-child-gkzf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: multi-component-child-gkzf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: multi-component-child-gkzf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/build-e2e-royw-tenant/build-suite-component-update-jtln/multi-component-child-gkzf@sha256:36f54521277ab0d760f7ccffc515812f6e1b5f7c5108383b6005cfe3752209b3
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
